version: "3.9"

services:

    wordpress:
        build:
            context: .
            dockerfile: Dockerfile.dev
            args:
                uid: ${HOST_UID:-33}
                gid: ${HOST_GID:-33}
                http_port: ${HOST_HTTP_PORT:-8080}
        image: egghdz-wordpress-local:php7.4
        restart: always
        ports:
            - "${HOST_HTTP_PORT:-8080}:80"
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
            WORDPRESS_DB_CHARSET: ${WORDPRESS_DB_CHARSET}
            WORDPRESS_DB_COLLATE: ${WORDPRESS_DB_COLLATE}
        volumes:
            - wordpress:/var/www/html
            - ./src/wp-content/plugins:/var/www/html/wp-content/plugins
            - ./src/wp-content/themes:/var/www/html/wp-content/themes
            - ./src/wp-content/uploads:/var/www/html/wp-content/uploads
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:latest
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "UTC"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
            MYSQL_USER: ${WORDPRESS_DB_USER}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: ${WORDPRESS_DB_HOST}
            PMA_USER: root
            PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            UPLOAD_LIMIT: 1024M
        restart: always
        ports:
            - "81:80"
        volumes:
            - /sessions
        depends_on:
            - ${WORDPRESS_DB_HOST}

volumes:
    mariadb:
    wordpress:
